### ISSUE TITLE
Translations broken on adding 3rd language

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/strings#3]
What’s going on here? I just ran ./strings.mac frontend/ on a branch off of `master` for [this PR](https://github.com/okTurtles/group-income/pull/1641) and all of a sudden strings is making nonsensical changes. Either adding incorrect translations (as with `"Dismiss message"` , `"Programming"`, and others) or outright deleting translations for strings that are still present in the codebase (e.g. for `"Invalid associated proposal."`)

https://github.com/okTurtles/group-income/pull/1641/commits/b938359dd58858a622443577ec665ed783b6734d#diff-128ce4091634a27cdd89094027164f3a8e705569f48d90a1148b91759d62d689R286-R351

Steps to reproduce:

1. Checkout GI `master`
2. `cp strings/{english,german}.strings`
3. Update translation near top as follows: `"\"No\" votes required to block a proposal" = "NICH NEINE!";`
4. Run `./strings.mac ./frontend/`

It doesn’t happen if you just run `./strings.mac frontend/` , it seems related to adding a new `german.strings`

**Comment by SGrondin** [comment]
Fixed in v2.2.1 https://github.com/okTurtles/strings/releases/tag/v2.2.1

It was due to buffer sharing in parallel code.
